name: "Publish Github Pages"
description: "Publish a static website to Github Pages"

inputs:
  source-directory:
    description: 'The source to publish to GitHub Pages. Defaults to "dist".'
    default: 'dist'
    required: true
  build-command:
    description: 'The yarn command used to build the project. Defaults to "build".'
    default: 'build'
    required: true
  destination-directory:
    description: 'The directory within the GitHub Pages branch to place the source files. ATTN: See the README for details.'
    required: true
    default: '.'
  commit-message:
    description: 'The messages of the commit to the gh-pages branch. Defaults to a generic message.'
    required: true
    default: 'Deploy to GitHub Pages'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        ${{ github.action_path }}/run.sh \
        '${{ github.action_path }}/dist/gh-pages/index.js' \
        '${{ github.action_path }}/dist/json/index.js' \
        '${{ inputs.source-directory }}' \
        '${{ inputs.build-command }}' \
        '${{ inputs.destination-directory }}' \
        '${{ inputs.commit-message }}'
